### ISSUE TITLE
Remove inoreader ADS 过期了

### ISSUE THREAD

**Issue by mephisX** [Hacksign/configs#2]
面板下方会有新的广告
![Snipaste_2019-10-15_10-03-31](https://user-images.githubusercontent.com/30206556/66794190-19660e00-ef33-11e9-8547-fe1a999a129f.png)

**Comment by Hacksign** [comment]
先尝试卸载这个插件， 然后退出inoreader登录状态， 重新安装插件后再登录inoreader看下。
曾经发现油候偶尔会抽风， 脚本不起作用。

**Comment by mephisX** [comment]
这个是新的广告，以前没有过的。我工作电脑，私人电脑都是十月份才出现的。刚才试了一下你说的操作步骤，好像还是有这个广告。

**Comment by Hacksign** [comment]
> 这个是新的广告，以前没有过的。我工作电脑，私人电脑都是十月份才出现的。刚才试了一下你说的操作步骤，好像还是有这个广告。

最近inoreader出了一个新的界面， 弹框让我试用来着，我没有试用。
是否是因为使用了这个新界面导致的？

目前我这边一切正常，无法复现你说的情况，请尝试如下操作：
点广告右上的关闭按钮， 看是否有弹出提示让你买会员什么的。
还有，请告知用的什么模式， 我目前用三列模式， 没有发现有广告。

不排除是运营商或路由器劫持， 需要进一步定位问题， 或者等我这里也出现你上面的这个情况。

**Comment by mephisX** [comment]
使用新界面之后广告反而消失了。
点广告右上的关闭按钮， 是有弹出购买会员的界面。
![image](https://user-images.githubusercontent.com/30206556/67136708-cfe03080-f25c-11e9-86e9-cb71d4363aa0.png)
视觉是这样设置的。不过今天试用新界面后，广告已经消失了。

**Comment by Hacksign** [comment]
> 使用新界面之后广告反而消失了。
> 点广告右上的关闭按钮， 是有弹出购买会员的界面。
> ![image](https://user-images.githubusercontent.com/30206556/67136708-cfe03080-f25c-11e9-86e9-cb71d4363aa0.png)
> 视觉是这样设置的。不过今天试用新界面后，广告已经消失了。

？？？
可是， 我还没有开始适配Beta版界面…………这么神奇的吗？

**Comment by mephisX** [comment]
adguard home 的功能？ 我路由器上有个这个

**Comment by Hacksign** [comment]
> adguard home 的功能？ 我路由器上有个这个

不排除， ADBlock的确可以屏蔽InoReader的广告。
前段时间还弹框提示来着， “误伤”这个插件了，最重要的是， 还不是必现问题， 一堆反馈的…………

**Comment by mephisX** [comment]
哈哈，新版多不错的。建议适配新版。
用了两天感觉比原来的要舒服点。
