### ISSUE TITLE
哥哥你的博客掉了

### ISSUE THREAD

**Issue by Ch4mpa9ne** [Hacksign/configs#3]
哥哥我想看你的博客[[笔记] 使用ESXi搭建一个调试病毒的虚拟网络 - Debugwar]
https://debugwar.com/article/build-a-virus-debug-environment-with-ESXi
我在网页快照右下方找到了你的id，请问这是你吗，急切的想看您的文章，求恢复或者把这篇文章的图片或pdf传下github吧，求求了

555本来想在Hacksign/Articles下提的Issues，下面好歹有个blog的标志。但是不知道为啥打开错了项目，见谅

**Comment by Hacksign** [comment]
> 哥哥我想看你的博客[[笔记] 使用ESXi搭建一个调试病毒的虚拟网络 - Debugwar] https://debugwar.com/article/build-a-virus-debug-environment-with-ESXi 我在网页快照右下方找到了你的id，请问这是你吗，急切的想看您的文章，求恢复或者把这篇文章的图片或pdf传下github吧，求求了
> 
> 555本来想在Hacksign/Articles下提的Issues，下面好歹有个blog的标志。但是不知道为啥打开错了项目，见谅

已修复

**Comment by Ch4mpa9ne** [comment]
感谢感谢
